repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        name: backend ruff
        args: [--exit-non-zero-on-fix]
        files: ^backend/
      - id: ruff
        name: tests ruff
        args: [--exit-non-zero-on-fix, --config=ruff.test.toml]
        files: ^tests/
      - id: ruff-format
        name: backend ruff check format
        args: [--check]
        files: ^backend/
      - id: ruff-format
        name: tests ruff check format
        args: [--check]
        files: ^tests/
