version: '3.3'
services:

  osm_front:
    build:
      context: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:1083

  osm_db:
    image: postgis/postgis:16-3.4
    volumes:
      - /var/lib/postgresql/data/
      - ./postgres/init:/docker-entrypoint-initdb.d
    env_file:
      - ./.env

  osm_redis:
    image: redis:latest

  osm_celery_worker:
    build:
      context: ../backend
    restart: always
    command: celery -A osm2you worker --loglevel=info
    depends_on:
      - osm_db
      - osm_redis
    env_file:
      - ./.env
  
  osm_celery_beat:
    build:
      context: ../backend
    restart: always
    command: celery -A osm2you beat -l INFO
    depends_on:
      - osm_db
      - osm_redis
    env_file:
      - ./.env

  osm_back:
    build:
      context: ../backend
    restart: always
    volumes:
      - osm_static_value:/backend/static/
      - osm_media_value:/backend/media/
    depends_on:
      - osm_celery_worker
      - osm_celery_beat
    env_file:
      - ./.env
    command: /scripts/startback.sh

  osm_nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - osm_static_value:/var/html/static/
      - osm_media_value:/var/html/media/
    depends_on:
      - osm_back

  osm_flower:
    build:
      context: ../backend
    restart: always
    command: /scripts/startflower.sh
    ports:
      - 5555:5555
    depends_on:
      - osm_celery_beat
    env_file:
      - ./.env


volumes:
  osm_static_value:
  osm_media_value: