"""Auto now created in trip model

Revision ID: 0d328842471a
Revises: 9a65570b2012
Create Date: 2024-09-27 14:14:44.737705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d328842471a'
down_revision: Union[str, None] = '9a65570b2012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trips_user_id_fkey', 'trips', type_='foreignkey')
    op.drop_constraint('trips_marker_id_fkey', 'trips', type_='foreignkey')
    op.create_foreign_key(None, 'trips', 'core_marker', ['marker_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'trips', 'core_user', ['user_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key('trips_marker_id_fkey', 'trips', 'core_marker', ['marker_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('trips_user_id_fkey', 'trips', 'core_user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
