# Generated by Django 4.0.10 on 2023-08-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markers", "0002_marker_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="add_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default="2022-09-20 10:27:21.240752",
                verbose_name="Add date",
            ),
            preserve_default=False,
        ),
    ]
