# Generated by Django 4.2.5 on 2023-11-06 10:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("markers", "0003_marker_add_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marker",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, unique=True
            ),
        ),
    ]
