# Generated by Django 4.2.5 on 2024-01-10 17:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markers", "0006_marker_osm_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkerCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("zoom", models.SmallIntegerField()),
                ("markers_count", models.IntegerField(default=0)),
                (
                    "update_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Update date"),
                ),
            ],
        ),
    ]
