# Generated by Django 4.2.5 on 2024-01-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markers", "0007_markercluster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markercluster",
            name="markers_count",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="markercluster",
            name="zoom",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
