# Generated by Django 4.2.5 on 2024-01-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markers", "0008_alter_markercluster_markers_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="markercluster",
            name="zoom",
        ),
        migrations.AddField(
            model_name="markercluster",
            name="square_size",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
