# Generated by Django 4.2.5 on 2024-01-27 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("markers", "0010_updatedmarkercluster"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="updatedmarkercluster",
            name="markercluster_ptr",
        ),
        migrations.DeleteModel(
            name="MarkerCluster",
        ),
        migrations.DeleteModel(
            name="UpdatedMarkerCluster",
        ),
    ]
