# Generated by Django 4.2.5 on 2024-01-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markers", "0012_markercluster_updatedmarkercluster"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="kind",
            field=models.CharField(
                choices=[("camp_site", "camp_site")], default="camp_site"
            ),
        ),
    ]
