# Generated by Django 4.2.5 on 2024-01-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markers", "0013_marker_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marker",
            name="kind",
            field=models.CharField(
                choices=[("camp_site", "Camp Site")], default="camp_site"
            ),
        ),
    ]
