# Generated by Django 4.2.5 on 2024-02-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markers", "0015_remove_marker_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkerKindGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("descriptive_name", models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
