# Generated by Django 4.2.5 on 2024-02-06 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("markers", "0016_markerkindgroup"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MarkerKindGroup",
        ),
    ]
