version: '3.3'
services:

  osm_front:
    build:
      context: ../frontend
    volumes:
      - ../frontend/:/app/result_build/

  osm_nginx:
    image: nginx:latest
    ports:
      - "1080:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      