# Generated by Django 4.2.5 on 2024-02-06 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0002_kindgroup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kindgroup",
            options={
                "ordering": ("-name",),
                "verbose_name": "Kind group",
                "verbose_name_plural": "Kinds groups",
            },
        ),
    ]
