# Generated by Django 4.2.5 on 2023-12-15 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("markers", "0004_alter_marker_location"),
        ("tags", "0003_alter_tag_options_tag_name_min_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creation date."
                    ),
                ),
                ("value", models.CharField(default=None, max_length=255, null=True)),
                (
                    "marker",
                    models.ForeignKey(
                        help_text="Choice marker",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_value",
                        to="markers.marker",
                        verbose_name="Marker",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="Specify value for tag",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_value",
                        to="tags.tag",
                        verbose_name="Tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag value",
                "verbose_name_plural": "Tags values",
                "ordering": ("-tag",),
            },
        ),
        migrations.AddConstraint(
            model_name="tagvalue",
            constraint=models.CheckConstraint(
                check=models.Q(("value__length__gte", 1)), name="value_min_length"
            ),
        ),
    ]
