# Generated by Django 4.2.5 on 2024-02-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("markers", "0017_delete_markerkindgroup"),
        ("tags", "0004_kind_kind_unique_kind_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkerKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        help_text="Choice kind value for marker",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kind_value",
                        to="tags.kind",
                        verbose_name="Marker Kind Value",
                    ),
                ),
                (
                    "marker",
                    models.ForeignKey(
                        help_text="Choice marker",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kind",
                        to="markers.marker",
                        verbose_name="Marker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marker kind value",
                "verbose_name_plural": "Markers kind value",
            },
        ),
        migrations.AddConstraint(
            model_name="markerkind",
            constraint=models.UniqueConstraint(
                fields=("kind", "marker"), name="unique_kind_marker_value"
            ),
        ),
    ]
