# Generated by Django 4.2.5 on 2023-12-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0004_tagvalue_tagvalue_value_min_length"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tagvalue",
            constraint=models.UniqueConstraint(
                fields=("tag", "model"), name="unique_marker_tag"
            ),
        ),
    ]
