# Generated by Django 4.2.5 on 2024-02-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0006_remove_markerkind_unique_kind_marker_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kind",
            name="kind_class",
            field=models.CharField(
                choices=[("main", "main"), ("related", "related")],
                default="related",
                help_text="Choice class for this kind",
                max_length=32,
                verbose_name="Kind class",
            ),
            preserve_default=False,
        ),
    ]
