# Generated by Django 4.2.5 on 2024-02-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0007_kind_kind_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kind",
            name="kind_class",
            field=models.CharField(
                choices=[("main", "main"), ("related", "related")],
                default="related",
                help_text="Choice class for this kind",
                max_length=32,
                verbose_name="Kind class",
            ),
        ),
    ]
