# Generated by Django 4.2.5 on 2024-02-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0008_alter_kind_kind_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="kind",
            name="priority",
            field=models.SmallIntegerField(
                default=2,
                help_text="Fill priority for this kind property",
                verbose_name="Kind priority",
            ),
        ),
    ]
