# Generated by Django 4.2.5 on 2024-02-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("markers", "0017_delete_markerkindgroup"),
        ("tags", "0009_kind_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markerkind",
            name="marker",
            field=models.OneToOneField(
                help_text="Choice marker",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kind",
                to="markers.marker",
                verbose_name="Marker",
            ),
        ),
    ]
