# Generated by Django 4.0.2 on 2022-05-14 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("markers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="Write you story", verbose_name="Text"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="stories/", verbose_name="Image"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "marker",
                    models.ForeignKey(
                        help_text="Choice marker",
                        on_delete=models.SET(0),
                        related_name="stories",
                        to="markers.marker",
                        verbose_name="Marker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story",
                "verbose_name_plural": "Stories",
                "ordering": ("-created",),
            },
        ),
    ]
