# Generated by Django 4.0.2 on 2022-05-15 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="image",
        ),
    ]
