# Generated by Django 4.2.5 on 2023-11-06 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stories", "0005_remove_story_author_remove_story_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="story",
            name="text",
            field=models.TextField(
                default="text", help_text="Write you story", verbose_name="Text"
            ),
            preserve_default=False,
        ),
    ]
