# Generated by Django 4.2.5 on 2023-11-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0006_story_author_story_text"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="story",
            constraint=models.CheckConstraint(
                check=models.Q(("text__length__gte", 10)), name="text_min_length"
            ),
        ),
    ]
