# Generated by Django 4.0.2 on 2022-05-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_bio_user_facebook_user_instagram_user_telegtam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegtam',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='telegram'),
        ),
    ]
