# Generated by Django 4.2.5 on 2024-02-13 13:47

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkerCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("square_size", models.FloatField()),
                ("markers_count", models.PositiveIntegerField()),
                (
                    "update_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Update date"),
                ),
            ],
            options={
                "verbose_name_plural": "Marker Clusters",
            },
        ),
        migrations.CreateModel(
            name="UpdatedMarkerCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("square_size", models.FloatField()),
                ("markers_count", models.PositiveIntegerField()),
                (
                    "update_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Update date"),
                ),
            ],
            options={
                "verbose_name_plural": "Updated Marker Clusters",
            },
        ),
        migrations.CreateModel(
            name="Marker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, unique=True
                    ),
                ),
                ("osm_id", models.BigIntegerField(blank=True, default=None, null=True)),
                (
                    "add_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Add date"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="markers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
        ),
    ]
