# Generated by Django 4.2.5 on 2024-02-13 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_kind_kindgroup_markerkind_tag_tagvalue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creation date."
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="Write you story", verbose_name="Text"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "marker",
                    models.ForeignKey(
                        help_text="Choice marker",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to="core.marker",
                        verbose_name="Marker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story",
                "verbose_name_plural": "Stories",
                "ordering": ("-created",),
            },
        ),
        migrations.AddConstraint(
            model_name="story",
            constraint=models.CheckConstraint(
                check=models.Q(("text__length__gte", 10)), name="text_min_length"
            ),
        ),
    ]
