# Generated by Django 4.2.5 on 2024-03-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_marker_id_relatedmarkerscrap_marker"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatedmarkerscrap",
            name="pack_index",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
