# Generated by Django 4.2.5 on 2024-03-24 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_relatedmarkerscrap_pack_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="kind",
            field=models.ForeignKey(
                default=None,
                help_text="Choice kind value for marker",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marker",
                to="core.kind",
                verbose_name="Marker Kind Value",
            ),
        ),
        migrations.AlterField(
            model_name="markerkind",
            name="kind",
            field=models.ForeignKey(
                help_text="Choice kind value for marker",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marker_kind_value",
                to="core.kind",
                verbose_name="Marker Kind Value",
            ),
        ),
        migrations.AlterField(
            model_name="markerkind",
            name="marker",
            field=models.OneToOneField(
                help_text="Choice marker",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marker_kind",
                to="core.marker",
                verbose_name="Marker",
            ),
        ),
    ]
