# Generated by Django 4.2.5 on 2024-03-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_delete_markerkind"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="marker",
            index=models.Index(
                fields=["location"], name="core_marker_locatio_8b2fb2_idx"
            ),
        ),
    ]
