# Generated by Django 4.2.5 on 2024-03-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_marker_core_marker_locatio_8b2fb2_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="marker",
            index=models.Index(
                fields=["kind_id"], name="core_marker_kind_id_3f8db5_idx"
            ),
        ),
    ]
