name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install --upgrade pip
        sudo apt-get install -y libgdal-dev
        pip install poetry
        mkdir log
        cd backend/
        poetry config virtualenvs.create false
        poetry install

    - name: Test with pytest
      env:
        ST_SECRET_KEY: +r@zjp=kc@qh#=ov6^vyvx0kb7g=11(*_^a3@%6en$-9_kr_)j
        DB_NAME: postgres
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_HOST: localhost
        DB_PORT: 5432
        GDAL_LIBRARY_PATH: /usr/lib/libgdal.so
      run: |
        pytest --reuse-db

  send_message:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} Completed successfully!
